#general information
client1.msg =Welcome to the CLIENTE1 applications
client1.build-version=1
client1.msg =Welcome to the CLIENTE1 applications
client1.build-version=1

#mail information
client1.mailDetails.hostName=sandrocordova99@hotmail.com
#client1.mailDetails.port=7400
client1.mailDetails.from=cordovasandro99@gmail.com
cliente1.mailDetails.subject=Practica para el cliente 1
spring.jpa.hibernate.ddl-auto=update
