#general information
client1.msg =Welcome to the PRODUCTOS applications
client1.build-version=1
client1.msg =Welcome to the PRODUCTOS applications
client1.build-version=1

#mail information
client1.mailDetails.hostName=sandrocordova99@hotmail.com
 
client1.mailDetails.from=cordovasandro99@gmail.com
client1.mailDetails.subject=Practica para el PRODUCTOS
 
