#general information
productos.msg =Welcome to the PRODUCTOS applications
productos.build-version=1
productos.msg =Welcome to the PRODUCTOS applications
productos.build-version=1

#mail information
productos.mailDetails.hostName=sandrocordova99@hotmail.com
 
productos.mailDetails.from=cordovasandro99@gmail.com
productos.mailDetails.subject=Practica para el PRODUCTOS
 
